### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-rodriguezmontesinoseva#1]
Super buen trabajo @rodriguezmontesinoseva !!!

Algunas pistas para acabarlo:

- [x] Saca la constante de pokemons fuera del componente App. De este manera solo la creamos una vez y no cada vez que se llame a render.
- [x] Pon el título (Mi lista de Pokemons) a nivel de página (App)
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Limpia e indenta el código
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by rodriguezmontesinoseva** [comment]
Hola Nasiba,

He resuelto las issues y he mejorado el estilo. 

Tengo dudas con los ficheros css. He hecho parciales con sass, y he llamado a index.scss desde los componentes, pero no sé si es correcto o debo llamar desde cada componente a su .scss.

Intentaré ir haciendo los “extra”

Gracias!

**Comment by nasivuela** [comment]
Excelente!

Respecto a los archivos de estilo: yo pondría cada uno junto a su componente de react y sería estos los encargados de importarlos, cada oveja con su pareja. En index.scss puedes tener estilos globales (body, html), resets... e importarlo en index.js.

Cierro issue, dejandote como recomendación que mires las consola de Chrome y apañes el error que aparece ;)

![](https://media.giphy.com/media/3oriO6rjsvAYwnvm0M/giphy.gif)
